services:
  - type: static
    name: shopwithme-frontend
    rootDir: client
    buildCommand: npm ci --production && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        sync: false
    plan: free
    region: oregon 