services:
  - type: web
    name: shopwithme-frontend
    env: static
    buildCommand: cd client && npm ci --only=production --package-lock=false && npm run build
    staticPublishPath: ./client/build
    envVars:
      - key: REACT_APP_API_URL
        sync: false 