services:
  - type: static
    name: shopwithme-frontend
    buildCommand: cd client && npm ci --production && npm run build
    staticPublishPath: ./client/build
    envVars:
      - key: REACT_APP_API_URL
        sync: false
    plan: free
    region: oregon 