services:
  - type: static
    name: shopwithme-frontend
    rootDir: client
    buildCommand: cd client && npm install --production && npm run build
    staticPublishPath: client/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://shopwithme-3o60.onrender.com
    plan: free
    region: oregon 