services:
  - type: web
    name: shopwithme-frontend
    env: static
    buildCommand: cd client && cp package.prod.json package.json && npm ci && npm run build
    staticPublishPath: ./client/build
    envVars:
      - key: REACT_APP_API_URL
        sync: false 